version: '3'

services:

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    ports:
      - 3306:3306
    networks:
      - nodenet

  node:
    build: 
      context: ./node
      dockerfile: Dockerfile
    # image: venilson/nodejs
    container_name: node
    networks:
      - nodenet
    tty: true
    volumes:
      - ./node:/usr/src/app
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    # image: venilson/nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - nodenet
  
networks:
  nodenet:
    driver: bridge
