version: '3'

services:

  node:
    build: 
      context: ./app
      dockerfile: Dockerfile
    # image: venilson/nodejs
    container_name: node
    networks:
      - nodenet
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    # image: venilson/nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - nodenet
  
networks:
  nodenet:
    driver: bridge
